# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwsVRX_8FxetCRPCliz84GSqZXI6GEKP
"""

import pandas as pd
import matplotlib.pyplot as plt

# Extract 2009 data
indmom_2009 = ind_mom.loc["2009"]
market_2009 = df["MktRf"].loc["2009"]

# Find worst 3 consecutive months
rolling3 = indmom_2009.rolling(3).sum()
worst_end = rolling3.idxmin()

worst_months = pd.date_range(end=worst_end, periods=3, freq="M")

print("Worst 3 consecutive momentum months:")
print(worst_months)

print("\nMomentum returns during crash months:")
print(indmom_2009.loc[worst_months])

print("\nMarket excess returns during crash months:")
print(market_2009.loc[worst_months])

print("\n3-month cumulative momentum return:")
print(rolling3.loc[worst_end])



# Momentum plot

plt.figure(figsize=(10,5))

plt.plot(indmom_2009.index,
         indmom_2009.values,
         marker='o')

plt.scatter(worst_months,
            indmom_2009.loc[worst_months],
            s=100)

plt.title("Industry Momentum Returns (2009)\nWorst 3 Consecutive Months Highlighted")

plt.xlabel("Month")
plt.ylabel("Return")

plt.grid(True)

plt.show()



# Market plot

plt.figure(figsize=(10,5))

plt.plot(market_2009.index,
         market_2009.values,
         marker='o')

plt.scatter(worst_months,
            market_2009.loc[worst_months],
            s=100)

plt.title("Market Excess Returns (2009)\nMomentum Crash Months Highlighted")

plt.xlabel("Month")
plt.ylabel("Market Excess Return")

plt.grid(True)

plt.show()


# Tables



indmom_2009.index.name = "date"
market_2009.index.name = "date"

print("\n2009 momentum returns:")
print(indmom_2009.round(6))

print("\n2009 market excess returns:")
print(market_2009.round(4))