# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvkMZoGHeLuMAwBSXtSL1lnit3yGsF6P
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv("Industry.csv")


df["date"] = pd.to_datetime(df["mdate"].astype(str), format="%Y%m")
df = df.drop(columns=["mdate"])
df = df.set_index("date")


for col in df.columns:
    df[col] = df[col].str.replace("%", "", regex=False)
    df[col] = pd.to_numeric(df[col], errors="coerce") / 100

industry_cols = [c for c in df.columns if c not in ["Rf", "MktRf"]]


past12 = df[industry_cols].rolling(12).mean().shift(1)
start = pd.Timestamp("1927-07-01")

past12 = past12.loc[past12.index >= start]
df = df.loc[df.index >= start]

ranks = past12.rank(axis=1, ascending=True)

winner_mask = ranks >= 16
loser_mask  = ranks <= 15

winner_ret = df[industry_cols].where(winner_mask).mean(axis=1)
loser_ret  = df[industry_cols].where(loser_mask).mean(axis=1)

indmom = winner_ret - loser_ret
mktrf = df["MktRf"]


indmom_2009 = indmom.loc["2009"]
market_2009 = mktrf.loc["2009"]


rolling3 = indmom_2009.rolling(3).sum()
worst_end = rolling3.idxmin()
worst_months = pd.date_range(end=worst_end, periods=3, freq="MS")

print("Worst 3 consecutive momentum months:")
print(worst_months)
print("\nMomentum returns:")
print(indmom_2009.loc[worst_months])

print("\nMarket excess returns during those months:")
print(market_2009.loc[worst_months])


plt.figure(figsize=(10,5))
plt.plot(indmom_2009)
plt.scatter(worst_months, indmom_2009.loc[worst_months], s=100)
plt.title("Industry Momentum Returns (2009)")
plt.show()


plt.figure(figsize=(10,5))
plt.plot(market_2009)
plt.scatter(worst_months, market_2009.loc[worst_months], s=100)
plt.title("Market Excess Returns (2009)")
plt.show()

indmom_2009.index.name = "date"
market_2009.index.name = "date"

print("2009 momentum returns:")
print(indmom_2009.round(6))

print("\n2009 market excess returns:")
print(market_2009.round(6))